version: '3.2'
services:
  menu_float_docker:
    platform: linux/arm64
    image: emirdeliz/flutter
    command: ["sh", "./menu_float/scripts/watch-test.sh"]
    ports:
      - 4002:4002
      - 35729:35729
      - 9191:9191
    stdin_open: true
    ipc: host
    volumes:
      - appcode-unison-sync:/home/docker/app:nocopy

volumes:
  appcode-unison-sync:
    name: appcode-unison-rsync-sync
